#!/usr/bin/env bash
# Autogenerated CyberAgent routine update script
# This script is responsible for the 24-hour sync of all intel DBs into Chroma.

echo "[*] Start RAG Database Update: $(date)"

echo "[*] Updating ExploitDB..."
# searchsploit -u uses apt update under the hood for exploitdb in Kali.
# Requires sudo if run manually, or root crontab.
if command -v searchsploit &> /dev/null; then
    sudo searchsploit -u || echo "Could not update searchsploit (maybe needs root)"
else
    echo "searchsploit not found. Install exploitdb package if on Debian/Kali."
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

if [ -f ".venv/bin/activate" ]; then
    echo "[*] Activating virtual environment..."
    source .venv/bin/activate
else
    echo "[!] Warning: No .venv found in $(pwd)! Running system python."
fi

echo "[*] Ingesting NVD CVEs, MITRE, and ExploitDB into ChromaDB memory banks..."
python3 knowledge_base/ingest_all.py --force

echo "[*] RAG Database Update Complete: $(date)"
